apiVersion: v1
kind: Namespace
metadata:
  name: npcl-voice-assistant
  labels:
    name: npcl-voice-assistant
    app: voice-assistant
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: voice-assistant-config
  namespace: npcl-voice-assistant
data:
  # Application Configuration
  GEMINI_MODEL: "gemini-1.5-flash"
  GEMINI_LIVE_MODEL: "gemini-1.5-flash"
  GEMINI_VOICE: "Puck"
  MAX_TOKENS: "150"
  TEMPERATURE: "0.7"
  
  # Audio Settings
  AUDIO_FORMAT: "slin16"
  AUDIO_SAMPLE_RATE: "16000"
  AUDIO_CHUNK_SIZE: "320"
  AUDIO_BUFFER_SIZE: "1600"
  
  # Voice Activity Detection
  VAD_ENERGY_THRESHOLD: "300"
  VAD_SILENCE_THRESHOLD: "0.5"
  VAD_SPEECH_THRESHOLD: "0.1"
  
  # Assistant Settings
  ASSISTANT_NAME: "ARI"
  VOICE_LANGUAGE: "en"
  LISTEN_TIMEOUT: "20.0"
  PHRASE_TIME_LIMIT: "15.0"
  VOICE_VOLUME: "0.9"
  
  # Logging
  LOG_LEVEL: "INFO"
  
  # Asterisk ARI Configuration
  ARI_BASE_URL: "http://asterisk-service:8088/ari"
  ARI_USERNAME: "asterisk"
  ARI_PASSWORD: "1234"
  STASIS_APP: "gemini-voice-assistant"
  
  # External Media Configuration
  EXTERNAL_MEDIA_HOST: "0.0.0.0"
  EXTERNAL_MEDIA_PORT: "8090"
  
  # Real-time Processing
  ENABLE_INTERRUPTION_HANDLING: "true"
  MAX_CALL_DURATION: "3600"
  AUTO_ANSWER_CALLS: "true"
  
  # Scalability Settings
  ENABLE_CLUSTERING: "true"
  CLUSTER_NODE_ID: ""  # Will be set by deployment
  SERVICE_DISCOVERY_TYPE: "kubernetes"
  
  # Observability
  METRICS_ENABLED: "true"
  METRICS_PORT: "9090"
  TRACING_ENABLED: "true"
  DASHBOARD_PORT: "8080"
  
  # Security
  SECURITY_ENABLED: "true"
  RATE_LIMITING_ENABLED: "true"
  INPUT_VALIDATION_ENABLED: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: voice-assistant-secrets
  namespace: npcl-voice-assistant
type: Opaque
data:
  # Base64 encoded secrets
  GOOGLE_API_KEY: ""  # Add your base64 encoded Google API key here
  JWT_SECRET_KEY: ""  # Add your base64 encoded JWT secret here
  ENCRYPTION_KEY: ""  # Add your base64 encoded encryption key here