apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
  namespace: npcl-voice-assistant
  labels:
    app: redis
    component: cache
spec:
  serviceName: redis-cluster-service
  replicas: 3
  selector:
    matchLabels:
      app: redis
      component: cache
  template:
    metadata:
      labels:
        app: redis
        component: cache
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        command:
        - redis-server
        - /etc/redis/redis.conf
        env:
        - name: REDIS_CLUSTER_ANNOUNCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis
        - name: redis-data
          mountPath: /data
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-service
  namespace: npcl-voice-assistant
  labels:
    app: redis
    component: cache
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: redis
    component: cache
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: npcl-voice-assistant
  labels:
    app: redis
    component: cache
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: redis
    component: cache
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: npcl-voice-assistant
data:
  redis.conf: |
    # Redis configuration for cluster mode
    port 6379
    bind 0.0.0.0
    protected-mode no
    
    # Persistence
    save 900 1
    save 300 10
    save 60 10000
    
    # Memory management
    maxmemory 200mb
    maxmemory-policy allkeys-lru
    
    # Logging
    loglevel notice
    
    # Replication (will be configured by cluster manager)
    # replica-read-only yes
    # replica-serve-stale-data yes